apiVersion: workspace.devfile.io/v1alpha2
kind: DevWorkspace
metadata:
  name: kai-coolstore-workspace
  namespace: admin-devspaces
  annotations:
    controller.devfile.io/displayName: Konveyor Kai + Coolstore
    controller.devfile.io/description: Explore the Coolstore microservices app with the Konveyor Kai AI extension in Dev Spaces
    icon: https://raw.githubusercontent.com/konveyor/editor-extensions/main/docs/assets/logo.png
    tags.devfile.io/devworkspace-type: sample,java,nodejs,ai
spec:
  started: true
  template:
    projects:
      - name: coolstore
        git:
          remotes:
            origin: https://github.com/rrbanda/coolstore.git
          checkoutFrom:
            revision: main

    components:
      - name: tools
        container:
          image: registry.redhat.io/devspaces/udi-rhel9:3.14
          cpuLimit: '4'
          cpuRequest: '1'
          memoryLimit: 8Gi
          memoryRequest: 4Gi
          mountSources: true
          sourceMapping: /projects
          env:
            - name: PYTHON_VERSION
              value: "3.11"
          args:
            - tail
            - -f
            - /dev/null
          endpoints:
            - name: frontend
              targetPort: 3000
              exposure: public
              protocol: https
            - name: backend
              targetPort: 8080
              exposure: public
              protocol: https
          volumeMounts:
            - name: m2
              path: /home/user/.m2
            - name: npm
              path: /home/user/.npm

      - name: m2
        volume:
          size: 1G

      - name: npm
        volume:
          size: 1G

    commands:
      - id: install-frontend
        exec:
          label: "Install Frontend Dependencies"
          component: tools
          workingDir: ${PROJECTS_ROOT}/coolstore/web-app
          commandLine: "npm install"
          group:
            kind: build

      - id: run-frontend
        exec:
          label: "Run Frontend"
          component: tools
          workingDir: ${PROJECTS_ROOT}/coolstore/web-app
          commandLine: "npm run dev"
          group:
            kind: run

      - id: build-backend
        exec:
          label: "Build Backend (Catalog Service)"
          component: tools
          workingDir: ${PROJECTS_ROOT}/coolstore/services/catalog
          commandLine: "mvn clean install"
          group:
            kind: build

      - id: run-backend
        exec:
          label: "Run Backend (Catalog Service)"
          component: tools
          workingDir: ${PROJECTS_ROOT}/coolstore/services/catalog
          commandLine: "mvn quarkus:dev"
          group:
            kind: run
