apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-from-openshift-devspaces
  namespace: admin-devspaces
spec:
  podSelector: {}  # Apply to all pods
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: openshift-devspaces
  policyTypes:
    - Ingress
